export enum ErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  AUTH_INVALID_REFRESH_TOKEN = 'AUTH_INVALID_REFRESH_TOKEN',
  USER_NOT_FOUND_OR_INACTIVE = 'USER_NOT_FOUND_OR_INACTIVE',
}
