export enum AuthErrorCode {
  AUTH_INVALID_REFRESH_TOKEN  = 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_INVALID_ACCESS_TOKEN   = 'AUTH_INVALID_ACCESS_TOKEN',
  USER_NOT_FOUND_OR_INACTIVE  = 'USER_NOT_FOUND_OR_INACTIVE',
}
